language: python
notifications:
  email: false
python:
  - "2.7"
install:
  - pip install -r requirements_test.txt
script:
  - pytest
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y liberasurecode-dev